# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Wooseok Park 박우석"
resume_title:                   ""

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hoeen5373@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>첫 데이터 분석 프로젝트에서 1저자로 SCIE급 논문을 써낸 <br>높은 잠재력의 소유자, 박우석입니다. <br><br>
  천문학 관측 데이터 분석을 통해 noisy한 데이터의 전처리 방법과 새로운 feature들을 <br>학계에 제안했으며 약 2700회 다운로드, 70회 이상 인용되는 성과를 낳았습니다.
  <br><br>
  이후 음성 분야에서 병렬처리를 활용한 Speech-To-Text 전사 속도 단축, <br>교육 분야에서 추천 파이프라인 최적화, 지식추적 AI 모델 개발을 담당하며 <br>다양한 AI 도메인에서 성과를 도출하였습니다. 
  <br><br>
  데이콘 대회 상위 4% 진입, 캐글 동메달 수여를 통해 <br>머신러닝 모델링 및 데이터 분석 실력을 검증하였으며,
  <br><br>
  사이드 프로젝트로 추천 모델을 통합한 SLM+RAG 챗봇으로 <br> 기존 SLM의 성능을 최대 65% 향상시켰고, <br> 한능검 추천 ai 프로젝트에서 실사용자 A/B테스트를 통해 KPI를 달성하는 등
  <br>개인화 추천 AI 서비스 기획 뿐 아니라 그 성과를 정량적으로 측정하려 노력하고 있습니다.
  <br><br>
  분석 논문을 기고한 경험을 통해 데이터 분석 결과를 효과적인 메시지로 전달하겠으며, <br>다양한 도메인에서의 머신러닝 경험을 바탕으로 <br>
  새로운 환경에 빠르게 적응하고 주어진 문제들을 해결하겠습니다. <br><br><br></p>"

# resume_header_intro: "<p>
#   사용자 지식 추적 및 추천 시스템 분야에서 경험을 쌓은 AI 개발자입니다.  <br>
#   잘 하는 일 보다는, 왜? 라는 물음을 갖게 되는 일을 더 좋아합니다. <br>
#   SCI급 논문 1저자로서의 연구 경험과 추천 AI 개발자로서의 경험을 바탕으로   <br>
#   현대카드의 초개인화 AI에 기여하는 데이터 과학자가 되겠습니다.
#   </p>"

# 천문학 SCI급 논문 1저자에서 AI 개발자까지, 다양한 분야에 금방 적응하고 발전하는 박우석입니다.
# 6년간의 장기적인 관측 데이터에서 별의 밝기 특성에 대한 인사이트를 발견, 8명의 공저자들과 함께 1저자로 논문을 게재한 경험이 있습니다.
# 이후 데이터 분석 및 인공지능 개발로 커리어를 전환, 추천 시스템 및 음성합성 분야에서 경험을 쌓아 왔습니다.
# 질문하는 것을 주저하지 않으며 새로운 도전을 늘 추구합니다. 빠르게 성장하고 팀의 fit에 잘 맞추는 분석가 및 개발자가 되겠습니다.


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true
resume_section_research:        true 


# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/hoeen"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/hoeen/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
